name: CI

on: [push, pull_request]

jobs:
  build:
    name: ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: amd64
            flags: -O3 -fomit-frame-pointer
          - target: x86
            flags: -m32 -O3 -fomit-frame-pointer
    steps:
      - uses: actions/checkout@v3
      - name: Prepare
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update -q -y
          sudo apt-get install -y gcc-multilib g++-multilib valgrind libc6-dbg libc6-dbg:i386
      - name: cmake build & test examples
        run: |
            mkdir build
            cd build
            cmake ..
            cmake --build .
            cd bin
            ./chan_1
            ./chan_2
            ./chan_3
            ./primes
            ./testdelay 2

  build-qemu:
    name: ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: arm
            arch: armv7
          - target: aarch64
            arch: aarch64
          - target: ppc64v2
            arch: ppc64le
    steps:
      - uses: actions/checkout@v3
      - uses: uraimo/run-on-arch-action@v2
        with:
          arch: ${{ matrix.arch }}
          distro: ubuntu_latest
          install: |
            apt-get update -q -y
            apt-get install -q -y --no-install-recommends build-essential valgrind
          env: |
            target: ${{ matrix.target }}
          run: |
            mkdir build
            cd build
            cmake ..
            cmake --build .
            cd bin
            ./chan_1
            ./chan_2
            ./chan_3
            ./primes
            ./testdelay 2


  build-windows:
    name: Windows (${{ matrix.arch }})
    runs-on: windows-2019
    strategy:
      fail-fast: false
      matrix:
        arch: [amd64, x86]
    steps:
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.arch }}
      - uses: actions/checkout@v3
      - name: cmake build & test examples
        run: |
            mkdir build
            cd build
            cmake .. -D CMAKE_GENERATOR_PLATFORM=Win32
            cmake --build .
            cd bin/Debug
            .\chan_1.exe
            .\chan_2.exe
            .\chan_3.exe
            .\primes.exe
            .\testdelay.exe 2
