name: CI-Qemu

on: [push, pull_request]

jobs:
  build-qemu:
    name: ${{ matrix.target }}
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: arm
            arch: armv7
          - target: aarch64
            arch: aarch64
          - target: ppc64v2
            arch: ppc64le
    steps:
      - uses: actions/checkout@v3
      - uses: uraimo/run-on-arch-action@v2
        with:
          arch: ${{ matrix.arch }}
          distro: ubuntu20.04
          install: |
            apt-get update -q -y
            apt-get install -q -y --no-install-recommends build-essential valgrind
          env: |
            target: ${{ matrix.target }}
          run: |
            mkdir build
            cd build
            cmake ..
            cmake --build .
            cd bin
            ./chan_3
            ./primes
            ./testdelay 2
